### ISSUE TITLE
Accessing proj from pdal within qgis

### ISSUE THREAD

**Issue by karl-magnus** [conda-forge/proj.4-feedstock#82]
Issue:
Hi!
I'm trying to run a pdal pipline in QGIS python console. When I invoke a pipeline with "spatialreference": or try to read from pg_pointcloud I get an error.<br/>
`Traceback (most recent call last):
  File "C:\Users\ikmjo01\Anaconda3\envs\pdaltest\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 20, in <module>
  File "C:\Users\ikmjo01\Anaconda3\envs\pdaltest\lib\site-packages\pdal\pipeline.py", line 40, in execute
    return self.p.execute()
  File "libpdalpython.pyx", line 166, in pdal.libpdalpython.PyPipeline.execute
RuntimeError: Could not import coordinate system 'EPSG:3008': PROJ: proj_create_from_database: Cannot find proj.db.`<br/>
If I use another pipeline that just read from a LAS-file without "spatialreference" it works in QGIS. The first pipeline works fine with "spatialreference" in Conda prompt.<br/>
Works in both QGIS and Conda prompt: <br/>
`json = """
[
    "C:/projekt/3d/las/6212_190.las",
    {
        "type":"filters.range",
        "limits":"Classification[2:2]"
    },
    {
        "filename":"C:/projekt/3d/las/test.las",
        "type": "writers.las"
    }
]
"""
import pdal
pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
print(count)`<br/>
Works only Conda prompt: <br/>
`json = """
[
    {
        "type":"readers.las",
        "filename": "C:/projekt/3d/las/6212_190.las",
        "spatialreference":"EPSG:3008"
    },
    {
        "type":"filters.range",
        "limits":"Classification[2:2]"
    },
    {
        "filename":"C:/projekt/3d/las/test2.las",
        "type": "writers.las"
    }
]
"""
import pdal
pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
metadata = pipeline.metadata
log = pipeline.log
print(count)`
<br/>

https://github.com/PDAL/python/issues/59

Environment (<code>conda list</code>):
<details>

```
# packages in environment at C:\Users\ikmjo01\Anaconda3\envs\pdaltest:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38ha419a9e_0    conda-forge
cfitsio                   3.470                he774522_5    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
coverage                  5.1              py38h1e8a9f7_0    conda-forge
cryptography              2.9.2            py38hba49e27_0    conda-forge
curl                      7.69.1               h1dcc11c_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
entwine                   2.1.0                h6cf58e4_3    conda-forge
exiv2                     0.27.1               hfa2c1cf_0    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gdal                      3.0.4            py38h3ba59e7_9    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.5.1               h3d29ae3_10    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.64.2               he4de6d7_0    conda-forge
gsl                       2.6                  h86b8168_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_ha405e13_100    conda-forge
httplib2                  0.17.3             pyh9f0ad1d_0    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
intel-openmp              2020.0                      166
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsoncpp                   1.8.4             h1ad3211_1002    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.17.1               hdd46e55_0    conda-forge
laszip                    3.4.3                h6538335_1    conda-forge
laz-perf                  1.4.4                ha925a31_0    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.69.1               h1dcc11c_0    conda-forge
libffi                    3.2.1             h6538335_1007    conda-forge
libgdal                   3.0.4                h6f60a84_9    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_104    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libpq                     12.2                 hd9aa61d_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h51df0ed_1038    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
libzip                    1.5.1             h8f0db0c_1005    conda-forge
lz4-c                     1.9.2                h62dcd97_1    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py38h1626042_0    conda-forge
mkl                       2020.0                      166
mock                      4.0.2            py38h32f6830_0    conda-forge
msys2-conda-epoch         20160418                      1
nitro                     2.7.dev6             he025d50_1    conda-forge
nose2                     0.9.2                      py_0    conda-forge
numpy                     1.18.4           py38h72c728b_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
owslib                    0.19.2                     py_1    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pdal                      2.1.0                h71384ab_4    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
plotly                    4.7.0              pyh9f0ad1d_0    conda-forge
poppler                   0.87.0               h0cd1227_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 he14cc48_1    conda-forge
proj                      7.0.0                haa36216_3    conda-forge
psycopg2                  2.8.5            py38hba49e27_1    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h1dd9442_0    conda-forge
pyqt                      5.12.3           py38h7ae7562_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.2           h5fd99cc_7_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-pdal               2.3.3            py38h6a11f7f_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
qca                       2.2.1                hd7ce7fb_3    conda-forge
qgis                      3.12.2           py38h488fe58_0    conda-forge
qjson                     0.9.0             hd7ce7fb_1006    conda-forge
qscintilla2               2.11.2           py38h19e3e1c_2    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtkeychain                0.10.0               hd7ce7fb_0    conda-forge
qtlocation                5.12.5               he025d50_0    conda-forge
qwt                       6.1.4             hd7ce7fb_1005    conda-forge
qwtpolar                  1.1.1                hd7ce7fb_7    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
sip                       4.19.22          py38hb99c5c2_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tbb                       2018.0.5             he980bc4_0
tiledb                    1.7.7                h0b90766_1    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
tornado                   6.0.4            py38hfa6e2cd_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
yaml                      0.2.4                he774522_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                h9f78265_3    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : pdaltest
    active env location : C:\Users\ikmjo01\Anaconda3\envs\pdaltest
            shell level : 3
       user config file : C:\Users\ikmjo01\.condarc
 populated config files : C:\Users\ikmjo01\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\ikmjo01\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ikmjo01\Anaconda3\pkgs
                          C:\Users\ikmjo01\.conda\pkgs
                          C:\Users\ikmjo01\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ikmjo01\Anaconda3\envs
                          C:\Users\ikmjo01\.conda\envs
                          C:\Users\ikmjo01\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by luipir** [comment]
Just to add more info. This arror happen only inside QGIS python console or also in a terminal under conda environment?

**Comment by luipir** [comment]
ho! sorry I can see you already answered in https://github.com/PDAL/python/issues/59#issuecomment-625671095

**Comment by karl-magnus** [comment]
Yes. It works fine in terminal under conda environment. So it's somehow QGIS related.

**Comment by luipir** [comment]
can you cut&paste the help->about->about of qgis? there there are all version used in the qgis build

**Comment by karl-magnus** [comment]
QGIS version | 3.12.2-București | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0-RC1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | DigitizingTools; Discovery; geomovetools; pdaltools; qfieldsync; db_manager; MetaSearch; processing

**Comment by luipir** [comment]
hmmmm... seems all correct with proj7

**Comment by karl-magnus** [comment]
All installed in a new environment in Conda with standard versions: conda install -c conda-forge pdal python-pdal gdal entwine matplotlib qgis

**Comment by karl-magnus** [comment]
If someone needs/have time to look in to it I'll talk to my boss and see what we can do. But first confirm the problem and estimate a solution.

**Comment by luipir** [comment]
had a friend having time to do a short test session on ubuntu... first tests are not positive but with different type of errors.
Import python-pdal works correctly but running pipeline generate crash. Sorry, I'm tring to fine time at least to replicate :/

**Comment by karl-magnus** [comment]
Thanks. For me everything works perfect except this thing with proj when using spatialreference or anything else that needs it.

**Comment by luipir** [comment]
FYI from pdal mailing list... 

http://osgeo-org.1560.x6.nabble.com/pdal-Pdal-2-1-0-and-libproj-td5438823.html

**Comment by karl-magnus** [comment]
Thanks. Sounds somehow related. But currently beyond my capability of handling software.

**Comment by xylar** [comment]
I'm going to close this issue since it's 5 years old.  Feel free to reopen if it happens to still be relevant.
